#!/bin/bash
echo "========================================================================================"
echo "                          QBOUND PROJECT STRUCTURE"
echo "========================================================================================"
echo ""
echo "📁 ROOT DIRECTORY"
echo "  README.md                    - Project overview and documentation"
echo "  CLAUDE.md                    - Instructions for Claude Code"
echo ""
echo "📦 src/                        - CORE COMPONENTS (shared by all experiments)"
echo "  ├── dqn_agent.py            - DQN agent with QBound implementation"
echo "  ├── environment.py          - GridWorld environment"
echo "  └── __init__.py             - Package initialization"
echo ""
echo "🔬 experiments/                - EXPERIMENT SCRIPTS (one folder per environment)"
echo "  ├── gridworld/              - GridWorld (10x10 grid)"
echo "  │   └── train_gridworld.py  - Train agent on GridWorld"
echo "  ├── frozenlake/             - FrozenLake (4x4, slippery)"
echo "  │   └── train_frozenlake.py - Train agent on FrozenLake"
echo "  ├── cartpole/               - CartPole (balance pole)"
echo "  │   └── train_cartpole.py   - Train agent on CartPole"
echo "  └── combined/               - Run all environments"
echo "      └── run_all_experiments.py - Run all 3 experiments"
echo ""
echo "📊 analysis/                   - ANALYSIS AND VISUALIZATION TOOLS"
echo "  ├── analyze_results.py      - Detailed analysis of results"
echo "  ├── comprehensive_analysis.py - Full analysis with plots"
echo "  ├── qbound_summary_table.py - Generate summary tables"
echo "  ├── show_qbound_config.py   - Show configuration analysis"
echo "  ├── track_q_values.py       - Track Q-value statistics"
echo "  ├── generate_plot.py        - Generate plots for paper"
echo "  └── update_paper_with_results.py - Update paper with results"
echo ""
echo "📝 docs/                       - DOCUMENTATION"
echo "  ├── ANALYSIS_SUMMARY.md     - Full analysis writeup"
echo "  ├── CHANGES.md              - Code change log"
echo "  └── explain_aux_weight.md   - Explanation of aux_weight"
echo ""
echo "💾 results/                    - EXPERIMENT RESULTS (auto-generated)"
echo "  ├── gridworld/              - GridWorld results"
echo "  ├── frozenlake/             - FrozenLake results"
echo "  ├── cartpole/               - CartPole results"
echo "  ├── combined/               - Combined results"
echo "  └── plots/                  - Generated plots"
echo ""
echo "========================================================================================"
echo "QUICK REFERENCE"
echo "========================================================================================"
echo ""
echo "🎯 TO RUN EXPERIMENTS:"
echo "  GridWorld:   python experiments/gridworld/train_gridworld.py"
echo "  FrozenLake:  python experiments/frozenlake/train_frozenlake.py"
echo "  CartPole:    python experiments/cartpole/train_cartpole.py"
echo "  All:         python experiments/combined/run_all_experiments.py"
echo ""
echo "📊 TO ANALYZE RESULTS:"
echo "  Quick table: python analysis/qbound_summary_table.py"
echo "  Detailed:    python analysis/analyze_results.py"
echo "  With plots:  python analysis/comprehensive_analysis.py"
echo ""
echo "========================================================================================"
